/*
 * This file is generated by jOOQ.
 */
package de.thb.ics.jooq.tables.records;


import de.thb.ics.jooq.tables.Station;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StationRecord extends UpdatableRecordImpl<StationRecord> implements Record5<String, LocalDate, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>station.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>station.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>station.date</code>.
     */
    public void setDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>station.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>station.target</code>.
     */
    public void setTarget(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>station.target</code>.
     */
    public Integer getTarget() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>station.actual</code>.
     */
    public void setActual(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>station.actual</code>.
     */
    public Integer getActual() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>station.variance</code>.
     */
    public void setVariance(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>station.variance</code>.
     */
    public Integer getVariance() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, LocalDate, Integer, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, LocalDate, Integer, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Station.STATION.ID;
    }

    @Override
    public Field<LocalDate> field2() {
        return Station.STATION.DATE;
    }

    @Override
    public Field<Integer> field3() {
        return Station.STATION.TARGET;
    }

    @Override
    public Field<Integer> field4() {
        return Station.STATION.ACTUAL;
    }

    @Override
    public Field<Integer> field5() {
        return Station.STATION.VARIANCE;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public LocalDate component2() {
        return getDate();
    }

    @Override
    public Integer component3() {
        return getTarget();
    }

    @Override
    public Integer component4() {
        return getActual();
    }

    @Override
    public Integer component5() {
        return getVariance();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public LocalDate value2() {
        return getDate();
    }

    @Override
    public Integer value3() {
        return getTarget();
    }

    @Override
    public Integer value4() {
        return getActual();
    }

    @Override
    public Integer value5() {
        return getVariance();
    }

    @Override
    public StationRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public StationRecord value2(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public StationRecord value3(Integer value) {
        setTarget(value);
        return this;
    }

    @Override
    public StationRecord value4(Integer value) {
        setActual(value);
        return this;
    }

    @Override
    public StationRecord value5(Integer value) {
        setVariance(value);
        return this;
    }

    @Override
    public StationRecord values(String value1, LocalDate value2, Integer value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StationRecord
     */
    public StationRecord() {
        super(Station.STATION);
    }

    /**
     * Create a detached, initialised StationRecord
     */
    public StationRecord(String id, LocalDate date, Integer target, Integer actual, Integer variance) {
        super(Station.STATION);

        setId(id);
        setDate(date);
        setTarget(target);
        setActual(actual);
        setVariance(variance);
    }
}
