/*
 * This file is generated by jOOQ.
 */
package de.thb.ics.service.station.jooq;


import de.thb.ics.service.station.jooq.tables.Station;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>station</code>.
     */
    public static final Station STATION = Station.STATION;
}
