/*
 * This file is generated by jOOQ.
 */
package de.thb.ics.repository.jooq;


import de.thb.ics.repository.jooq.tables.Station;
import de.thb.ics.repository.jooq.tables.records.StationRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<StationRecord> KEY_STATION_PRIMARY = Internal.createUniqueKey(Station.STATION, DSL.name("KEY_station_PRIMARY"), new TableField[] { Station.STATION.ID }, true);
}
